# This is a basic workflow to help you get started with Actions

name: Linux Automated build and client/server unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Lint files
        run: npm run lint

      - name: Build library
        run: npm run build

      - name: Run node unit tests
        run:  NODE_ENV=production npm run test:node

      - name: Run browser unit tests
        run:  NODE_ENV=production npm run test:chromium
      
      - name: Run old unit tests
        run: NODE_ENV=production npm run oldtest
