# This is a basic workflow to help you get started with Actions

name: Mac OS ARM Automated cross build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-macosarm:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive   

      - name: Install icu libs
      # modified snippet from https://github.com/Homebrew/discussions/discussions/2843
        run: | 
          mkdir -p ../armhomebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C ../armhomebrew 
          echo "Step1 finished"
          #../armhomebrew/bin/brew fetch --force --bottle-tag=arm64_big_sur icu4c | grep "Downloaded to"
          response=$(../armhomebrew/bin/brew fetch --force --bottle-tag=arm64_big_sur icu4c | grep "Downloaded to")
          echo "Step2 finished with response $response"
          parsed=($response)  
          echo "Step3 install ${parsed[2]}"
          ../armhomebrew/bin/brew install ${parsed[2]}
          echo "Step4"
          echo "icu4c will be in $(../armhomebrew/bin/brew --prefix)/opt/icu4c"
          echo "LOCALHOMEWBREWICU=\"$(../armhomebrew/bin/brew --prefix)/opt/icu4c\"" >> $GITHUB_ENV
        
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: Build library
        run: BUILDARCH=arm64 npm run build
        
#      - name: Run unit tests
#       run: NODE_ENV=production npm test
